### ISSUE TITLE
Windows line ends in npm package

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss#16]
https://registry.npmjs.org/sprucecss/-/sprucecss-2.3.0.tgz

e.g. in `scss/spruce-styles.scss`

Please consider publishing the npm package from here, from GitHub.

**Comment by adamlaki** [comment]
Good idea Viktor, will do!

**Comment by szepeviktor** [comment]
All right.

**Comment by adamlaki** [comment]
Do you want to help with the workflow file?

**Comment by szepeviktor** [comment]
No.

**Comment by szepeviktor** [comment]
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
