### ISSUE TITLE
Spelling Issues on Pagination

### ISSUE THREAD

**Issue by ksindhi** [conedevelopment/sprucecss#8]
I found spelling issues on Pagination Component

**To Reproduce**
1. Go to 'https://sprucecss.com'
2. Click on 'components'
3. Scroll down to 'Pagination'
4. See error on the right side for "defualt" 

**Expected behavior**
Spelling must be "default"

**Comment by adamlaki** [comment]
Hello,

Thank you for your contribution!

I've just fixed this typo and also two others with the exact spelling mistake (post author, accordion card).
